### ISSUE TITLE
self.configの引数でエラーが発生

### ISSUE THREAD

**Issue by clay7614** [okata-t/yt-dlp_GUI#7]
ついさっきコミットされた箇所でエラーが発生してる
以下エラー発生個所、エラー内容

```
94    def load_option(self):
95        self.var_chk_audio.set(self.config["Option"]["download_audio"])
96        self.var_chk_thumbnail.set(self.config["Option"]["embed_thumbnail"])
```

Traceback (most recent call last):
  File "c:\Users\Owner\Documents\GitHub\yt-dlp_GUI\main.py", line 324, in <module>
    app = App()
          ^^^^^
  File "c:\Users\Owner\Documents\GitHub\yt-dlp_GUI\main.py", line 33, in __init__
    self.load_option()
  File "c:\Users\Owner\Documents\GitHub\yt-dlp_GUI\main.py", line 95, in load_option
    self.var_chk_audio.set(self.config["Option"]["download_audio"])
                           ~~~~~~~~~~~^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\configparser.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'Option'

**Comment by okata-t** [comment]
config.iniを削除したら作成しなおされると思います

**Comment by clay7614** [comment]
上手く動いた
